# Generated by Django 5.2.1 on 2025-05-23 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อข่าว')),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish_date', verbose_name='Slug')),
                ('content', models.TextField(verbose_name='เนื้อหาข่าว')),
                ('excerpt', models.TextField(blank=True, verbose_name='บทคัดย่อ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/%Y/%m/%d/', verbose_name='ภาพปก')),
                ('status', models.CharField(choices=[('draft', 'แบบร่าง'), ('published', 'เผยแพร่'), ('archived', 'จัดเก็บ')], default='draft', max_length=10, verbose_name='สถานะ')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='จำนวนการเข้าชม')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่เผยแพร่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เขียน')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='หมวดหมู่')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag', verbose_name='แท็ก')),
            ],
            options={
                'verbose_name': 'ข่าว',
                'verbose_name_plural': 'ข่าวทั้งหมด',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/attachments/%Y/%m/%d/', verbose_name='ไฟล์แนบ')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='=ชื่อไฟล์')),
                ('file_type', models.CharField(choices=[('file', 'ไฟล์'), ('video', 'วิดีโอ'), ('audio', 'เสียง'), ('document', 'เอกสาร')], default='file', max_length=10, verbose_name='ประเภทไฟล์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.article', verbose_name='ข่าว')),
            ],
            options={
                'verbose_name': 'ไฟล์แนบ',
                'verbose_name_plural': 'ไฟล์แนบ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/%Y/%m/%d/', verbose_name='ภาพประกอบ')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='คำบรรยายภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.article', verbose_name='ข่าว')),
            ],
            options={
                'verbose_name': 'ภาพข่าว',
                'verbose_name_plural': 'ภาพข่าว',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date'], name='news_articl_publish_345e4d_idx'),
        ),
    ]
