# Generated by Django 5.2.1 on 2025-05-23 06:28

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_articleattachment_articleimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.get_file_upload_path, verbose_name='ภาพปก'),
        ),
        migrations.AlterField(
            model_name='articleattachment',
            name='file',
            field=models.FileField(upload_to=news.models.get_file_upload_path, verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to=news.models.get_file_upload_path, verbose_name='ภาพประกอบ'),
        ),
    ]
