# Generated by Django 5.1.7 on 2025-04-01 08:04

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_event', '0003_event_description_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
