# Generated by Django 5.2.1 on 2025-05-26 07:28

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวเรื่อง')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='เผยแพร่')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='คำอธิบายสำหรับ SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.category', verbose_name='หมวดหมู่')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เขียน')),
            ],
            options={
                'verbose_name': 'หน้า',
                'verbose_name_plural': 'หน้า',
                'ordering': ['-created_at'],
                'permissions': [('can_publish_page', 'สามารถเผยแพร่หน้าได้'), ('can_edit_page', 'สามารถแก้ไขหน้าได้')],
            },
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='หัวเรื่องส่วน')),
                ('content', models.TextField(blank=True, null=True, verbose_name='เนื้อหา')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page', verbose_name='หน้า')),
            ],
            options={
                'verbose_name': 'ส่วนเนื้อหา',
                'verbose_name_plural': 'ส่วนเนื้อหา',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='รองรับไฟล์ .PDF, .DOCX, .XLSX เท่านั้น', upload_to=pages.models.get_upload_path, verbose_name='ไฟล์')),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('title', models.CharField(help_text='ชื่อไฟล์ที่จะแสดง', max_length=200, verbose_name='ชื่อไฟล์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำบรรยายไฟล์')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนดาวน์โหลด')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('file_type', models.CharField(default='file', editable=False, max_length=50, verbose_name='ประเภทไฟล์')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.page', verbose_name='หน้า')),
            ],
            options={
                'verbose_name': 'ไฟล์ดาว์นโหลด',
                'verbose_name_plural': 'ไฟล์ดาว์นโหลด',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='รองรับไฟล์ .jpg, .png, .gif เท่านั้น', upload_to=pages.models.get_upload_path, verbose_name='รูปภาพ')),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำบรรยายภาพ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('file_type', models.CharField(default='image', editable=False, max_length=50, verbose_name='ประเภทไฟล์')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.page', verbose_name='หน้า')),
            ],
            options={
                'verbose_name': 'รูปภาพหน้า',
                'verbose_name_plural': 'รูปภาพหน้า',
                'ordering': ['order'],
            },
        ),
    ]
