# Generated by Django 5.2.1 on 2025-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='pagefile',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
