# Generated by Django 5.2.1 on 2025-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_category_page_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='sections', to='pages.pageimage', verbose_name='รูปภาพประกอบส่วนเนื้อหา'),
        ),
    ]
