# Generated by Django 5.1.7 on 2025-04-01 03:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.models.get_slide_upload_path, verbose_name='Image'),
        ),
    ]
